### PR TITLE
Update ceton status web page

### PR DESCRIPTION
**Pull request by arrmo**

### CODE REVIEW

**Comment by DanAustinGH** [comment]
The 1st part is good, but the second won't always work  If the PCI is the first device and there is only one, it is fine.  Say it is the second device, then the tuner instance is going to be 7, assuming the first device is a six tuner unit.  If we pull in tunerstatus we can check if ceton_pcie and in that case use ['streamurl'] in the call to devinuse

**Comment by arrmo** [comment]
Good point! Glad you're keeping me honest 😜.

OK, I see it getting a bit more funky then. I say that because ...
1. As we loop through the tuners, need to "break" between devices ... NP, but,
2. Need to know if each device is internal or external. They may be in either order ... right? I'm assuming you have checked that somewhere? And ... what if there are 2 PCIe cards? I guess we just increment that when switching tuners, and finding the second PCIe?

BTW, it seems what I had stored in `stream_info` (in Ceton status), you have also added that, e.g. streamurl. Should I remove `stream_info`?

Thanks!

**Comment by DanAustinGH** [comment]
I got on a roll and just kept adding code, not noticing what you had there in stream_info.  I am not married to streamurl.  I picked the name based on the immediate use case.

I set ceton_pcie to true if it is an internal.  We could make that an int and set it to zero for ethernet and increment a special counter for each HW device found.  Which is on my mental roadmap.  Although I wonder how long I will be the only person with multiple devices actually in use.    The code that tests the ceton_pcie  should not need major changes, if any.

This points one advantage of pre-generating the streamurl.  We do not really have to care about the parent device, we can refer to the keys ceton_pcie, streamurl, seton_tuner in tunerstatus to learn most (all?) we need about the device.  In fact I think I could randomize the instance so that the devices tuners were not grouped together and the code would still function.  It would be pointless to do that, but it means that the tunerstatus dict has most (all?) the critical keys.

**Comment by arrmo** [comment]
> I got on a roll and just kept adding code, not noticing what you had there in stream_info. I am not married to streamurl. I picked the name based on the immediate use case.

No worries! I'm fine removing stream_info, just wanted to make sure I wouldn't mess you up.



> The code that tests the ceton_pcie should not need major changes, if any.

Agreed!



> This points one advantage of pre-generating the streamurl. We do not really have to care about the parent device, we can refer to the keys ceton_pcie, streamurl, seton_tuner in tunerstatus to learn most (all?) we need about the device. In fact I think I could randomize the instance so that the devices tuners were not grouped together and the code would still function. It would be pointless to do that, but it means that the tunerstatus dict has most (all?) the critical keys.

Agreed! Do you want me to update the tuner status table using these? streamurl would work ... for the logic also regarding Direct (want me to make that Hardware?) and RTP. Like you say, if it's handled / sequenced, just use that!

**Comment by DanAustinGH** [comment]
And I missed point 1.  We could add a new device dict that has keys for device type, tuner count, IP etc.  Rough it

tuner = 0
for i in len(device{}):
    %code to get env details%
    for x in devvice[i][tuner_count]:
       tuner += 1
       %existing code that displays each tuner%

And to you latest post, if you can use those keys, go for it.  I think they might be enough which is why I had not added the device dict.  If they are not we can use the idea at the start of this post.

**Comment by arrmo** [comment]
WFM! Let's see if I can get the status showing properly based on those ... then that is clean, and behind the scenes we can renumber, etc. => it will just ripple up to the status, hopefully unchanged.

**Comment by arrmo** [comment]
Actually ... 😜. OK to keep stream_info? Because ... fHDHR passes back stream_args (with stream_info) inside it, to,
```
    def close_stream(self, instance, stream_args):
        closetuner = stream_args["stream_info"]["tuner"]
        self.plugin_utils.logger.noob('Closing Ceton tuner %s (fHDHR tuner %s)' % (closetuner, instance))
        self.startstop_ceton_tuner(closetuner, 0)
        return
```

Will still use the new vars for the status html, but rather than messing with the information passed back to `close_stream`. OK?

**Comment by DanAustinGH** [comment]
I rechecked and yes keep it.  It was never a dup.  It serves a function needed by the core, and tunerstatus has way more internal details that the core does not need or even use.  They are complimentary.

**Comment by arrmo** [comment]
Agreed! Think I found an easy change here to get it all working - and even fixes a latent bug that was waiting in the shadows for us ... LOL. Now, if I can get my daughter off the TV, I can check it 😆

**Comment by arrmo** [comment]
BTW, another fix I'll push, if OK with you - this one bit me earlier as well 😄.

In `get_ceton_tuner_status`, this needs to change slightly,
```
            if (transport == "STOPPED") and (not hwinuse):
                self.plugin_utils.logger.info('Selected Ceton tuner#: %s' % instance)
                # And, clear tunerstatus (just in case external client stopped using it)
                self.tunerstatus[str(instance)]['status'] =  "Inactive"
```
changes to,
```
            if (transport == "STOPPED") and (not hwinuse):
                self.plugin_utils.logger.info('Selected Ceton tuner#: %s' % instance)
                # And, clear tunerstatus (just in case external client stopped using it)
                self.tunerstatus[str(instance)] =  { "status": "Inactive" }
```

If not, once Inactive, you still see this,
```
"0": {
"ceton_ip": "192.168.200.1",
"ceton_pcie": true,
"ceton_tuner": "0",
"port": 8000,
"status": "Inactive",
"stream_args": {
"accessed": "http://192.168.2.64:5006/api/tuners?method=stream&channel=4c309db8-6bd7-4853-82b1-1730309e4c55&origin=ceton",
"base_url": "http://192.168.2.64:5006/",
"buffer_size": 3,
"bytes_per_read": 1152000,
"channel": "593",
"channel_callsign": "Golf HD",
"channel_name": "Golf HD",
"client": "192.168.2.64",
"client_id": "173178a5-6085-4a85-b4c5-725f9a9754b5",
"content_type": "video/mpeg",
"duration": 0,
"method": "ffmpeg",
"origin_name": "ceton",
"origin_quality": null,
"stream_info": {
"headers": null,
"tuner": "0",
"url": "/dev/ceton/ctn91xx_mpeg0_0"
},
"stream_restore_attempts": 3,
"transcode_quality": "working-3.14",
"true_content_type": "video/mpeg",
"tuner_number": null
},
"streamurl": "/dev/ceton/ctn91xx_mpeg0_0"
},
```

Make sense? And OK with you?

**Comment by arrmo** [comment]
Hmmm ... actually, you have other info stored there now. Perhaps just remove `stream_args`?

**Comment by DanAustinGH** [comment]
That was a change made on purpose.  It took me 30 minutes to notice the syntax and kept wondering why my dict was empty after init ran.  Setting status to inactive and stream_args to {} would be a happy medium

**Comment by arrmo** [comment]
> It took me 30 minutes to notice the syntax and kept wondering why my dict was empty after init ran.

LOL - ya, I can believe that. Sorry!



> Setting status to inactive and stream_args to {} would be a happy medium

Agreed! Done 👍

**Comment by arrmo** [comment]
OK, now you threw me a curveball - I guess turnabout is fair play ... LOL.

I was modifying `devinuse` in `__init__.py`, and it wasn't working - then I noticed you made a "copy" in `ceton_html.py`. No wonder my changes didn't work ... LOL. Like above - you married to the one in `ceton_html.py`? I admit, I'd like to keep it in one place, avoid fixing findings twice.

Thoughts?

Thanks!

**Comment by arrmo** [comment]
Never mind - I may have done that ... LOL. But I may need to find a better way now, to deal with the "shared" state. Give me just a bit digging.

**Comment by DanAustinGH** [comment]
Devices is just a list view of the ceton_ip
Since the config entry tuners is required by the core and cannot be a list I added device_tuners 

Example-
[ceton]
ceton_ip = 192.168.200.1,192.168.1.17  // in priority order
device_tuners = 6,4                                // same order as ceton_ip, device1 has 6 tuners, device2 has 4
tuners = 10                        // Sum of device_tuners

**Comment by arrmo** [comment]
That will work, perfect - thanks!

One more dumb question, but I'm not seeing it 😞. You use `tuner_tmp_count`, but it seems to me that it's just equal to `i`, no? Or are you shifting it from device to device? I'm thinking you are, but not seeing it (yet).

**Comment by DanAustinGH** [comment]
tuner_tmp_count represents the total tuners.  At the start of each device i is reset to zero and increments for each device tuner.  tuner_tmp_count also increments for each device tuner but does not get reset, so using the example above:
      The last tuner in the 1st device:  tuner_tmp_count = 5, i =5
      The first tuner in the 2nd device: tuner_tmp_count = 6, i =0

Hope that makes sense

**Comment by DanAustinGH** [comment]
If you want to see it in action, you can add the same IP multiple times in the ceton_ip list and build a large tunerstatus dict to see the format.  You cannot obviously use the extra tuners.

Which reminds me I should add an error case if the number of devices does not match the number of device_tuners entries

**Comment by arrmo** [comment]
Makes complete sense, thanks! The zip had me a bit confused, got it now. And ... adding about 2 lines, and status can also include the `ceton_device`, not just tuner ...
```
"0": {
"ceton_device": "0",
"ceton_ip": "192.168.200.1",
"ceton_pcie": true,
"ceton_tuner": "0",
"port": 8000,
"status": "Inactive",
"stream_args": {},
"streamurl": "/dev/ceton/ctn91xx_mpeg0_0"
},
```

Can just pull this, to use in the status table (and other items if needed).

**Comment by arrmo** [comment]
ARRGH! Was pulling my hair out with jinja2. But finally. Thoughts?
image

Thanks!

**Comment by DanAustinGH** [comment]
The zip was a suggestion from @deathbybandaid.  It worked, so I did not dig further...

I actually was OK with the tuners being lumped together.  What I though folks would want is to see the first six rows for each device (setup/temp/type/etc).

**Comment by arrmo** [comment]
> The zip was a suggestion from @deathbybandaid. It worked, so I did not dig further...

And it works great! I just had to figure it out 😆 



> I actually was OK with the tuners being lumped together. What I though folks would want is to see the first six rows for each device (setup/temp/type/etc).

Sorry, you lost me there. Are you referring to the picture I pasted above? They are lumped by device, tuners within that device. Not what you were thinking?

**Comment by DanAustinGH** [comment]
I do not feel strongly about grouping the tuners, so what you have is useful.

Lets look at the very first row in the table-
Setup  |    Success

That can either be the plugin status, of the 1st device status.  Let's say plugin, no change need.

The second row:
Temperature  |  64.9 C

That is clearly the first device, do we care about the 2nd+  I think so.

So my quandary has been do we have a separate table like it was for each device, or do we try to add dynamically sized columns for the device status rows:
Temperature        |  64.9 C | 80.5C
Hardware Type    |  PCI      | Ethernet
etc...

And keep the tuners in a common section.  A separate table for each device is easier to code, the dynamic columns seems like a PITA, but visually more appealing...

**Comment by arrmo** [comment]
Ahh, gotcha! And never thought of that. What if that top section were also "inside" the Device? That would be pretty easy, just where to loop over.

Thoughts?

**Comment by DanAustinGH** [comment]
Yeah, that is what I describe as the first option, one table per device.  In fact that would be a fine first step even if we eventually want to move to a single table view

**Comment by arrmo** [comment]
Got it - give me just a bit 🤣

**Comment by arrmo** [comment]
Thoughts? I put a blank line between => I could make it 1 table, but kinda liked the separation. Can be removed though. And yes, I have 1 device, so they look similar ... LOL
image

**Comment by DanAustinGH** [comment]
Like the space and that works perfect.  Commit when you are ready and I will merge

**Comment by arrmo** [comment]
Should be there now (commit updated). Please try it out - of course I can only fake out 2 devices 😆 

Thanks!

**Comment by arrmo** [comment]
FYI, also fixed a latent issue I noticed - hard coded /dev path ... using streamurl now!

**Comment by arrmo** [comment]
Thanks! Please let me know how it works for your (real) 2-device setup. Hopefully all smooth 😄

**Comment by DanAustinGH** [comment]
Will be trying on Monday.  Spent time reviewing my array health and it is Ok, but I am out of spares and of course the new ones are coming via the slowest method possible.  I doubt that the plugin was involved, but would rather be running all possible spares before the next attempt...

**Comment by arrmo** [comment]
NP, fully understand! And no panic. Hopefully your array is all happy again soon. If there are (plugin) issues, we'll get them fixed of course.

And, as soon as this got merged - I found one, thanks Mr. Murphy ... LOL. I only found it when I went back to the single device case, the issue line of code is,
```
            origin_status_dict = {"Devices": len(self.fhdhr.config.dict["ceton"]["device_tuners"])}
```
`len()` works fine for > 1 tuners, but with 1 ... `self.fhdhr.config.dict["ceton"]["device_tuners"]` is an int. Minor, but I just need to fix it. My preferred approach is a list with a length of 1, so consistent then.

Thanks!

**Comment by arrmo** [comment]
OK, one liner fix 🤣 
```
        device_tuners = self.device_tuners
        if not isinstance(device_tuners, list):
            device_tuners = [device_tuners]
            self.config_dict["device_tuners"] = device_tuners
```

Added the last line. Not sure why to "fix" the list only for the local variable - thoughts? And do the same for devices (store to dict)?

Thanks!

**Comment by arrmo** [comment]
Done! #38

**Pull request merged**
