### PR TITLE
Client + Minor Comment Update

### PR DESCRIPTION
**Pull request by arrmo**
As the commits capture,
- Client tool, to exercise Ceton plugin / fHDHR
- Minor update, comment to clarify about External state

Thanks!

And as requested, flagging to @DanAustinGH 😄

### CODE REVIEW

**Comment by DanAustinGH** [comment]
The note about external seems reasonable.  I gather that the client tool is to exercise the tuners and allow for automated testing?

If so, maybe add a few more notes about the parameters, and note that the ffmpegcli needs to be edited with the IP of the fHDHR host.  I do not object to adding a tool to the plugin to aid other developers to the package, but I'ds like to get @deathbybandaid to sign off before merging.

**Comment by deathbybandaid** [comment]
Wouldn't the client be better in the core repo, or it's own repo?

**Comment by arrmo** [comment]
> I gather that the client tool is to exercise the tuners and allow for automated testing?

Correct! Thinking (down the road) about CI type testing?




> Wouldn't the client be better in the core repo, or it's own repo?

Good point! And agreed. Do you have a preference? Thanks!

**Comment by deathbybandaid** [comment]
I'm leaning towards it having it's own repo and to take cli arguments, including a `--config` to point at a .ini

**Comment by arrmo** [comment]
Sure, works for me. As I am git-idiot 😜 ... do I kill this PR, break it into 2 (1 for the comment, 1 for the client - after mods)?

And do you want to set up that new repo, where you'd like it?

Thanks!

**Comment by arrmo** [comment]
Added a bit more documentation, and exit code checks.

Just let me know where you want client.py stored. Thanks!

**Comment by DanAustinGH** [comment]
I do not have a strong opinion about the client.  Maybe host it in a repo in your git account and add a link to that repo in the Readme?

**Comment by arrmo** [comment]
I'm fine with that too, no issue here! @deathbybandaid , do you have a preference?

I do find it handy, just figured I'd share - but this works as well (and still shares). I ran it again tonight, let it cycle for an hour ... no issues 👍.

Was thinking this could be CI (later?)?

Thanks!

**Comment by arrmo** [comment]
BTW, I have another utility I created here also ... for my Windows box (OS) - it's a tray application that shows me if tuners are in use. I miss the LED's I had on the external box, this way I know if someone is using a tuner, and I don't reboot the server at the wrong time. I'd be in deep doodoo 😜 

Not sure if we keep these all in 1 place or not? Or I can just keep them (my repository), and point at them. Like I noted above, also wondering about CI for new pushes.

Thanks!

**Comment by DanAustinGH** [comment]
Sounds like a handy little tool.  I'd say having a repo with related monitoring/testing addons make sense.  And I am not ignoring the CI question, I just have nothing to add to that discussion...

**Comment by arrmo** [comment]
LOL! No worries at all. I have my own local Gitlab server, and CI is quite easy. Basically just run the script, make sure the exit code is "correct". But I'm not sure how to do it on GitHub 😞.

Will let @deathbybandaid comment - I'm OK with the repository here, or just point to it. No strong preference really. Again, just trying to share. Well, and stay out of trouble (with the active tuner monitor) 🤣

**Comment by DanAustinGH** [comment]
If you have a public github repo I would suggest hosting the testing tool and adding a link referencing that location in the readme.  I do not have strong feeling but think that @deathbybandaid is right that testing tools should be their own repo. 

And since the last update with the locks added I have had zero instances of the system not working as expected or orphaned tuners.

**Comment by arrmo** [comment]
> If you have a public github repo I would suggest hosting the testing tool and adding a link referencing that location in the readme. I do not have strong feeling but think that @deathbybandaid is right that testing tools should be their own repo.

I could put it on GitHub - just a separate repository. Thoughts?



> And since the last update with the locks added I have had zero instances of the system not working as expected or orphaned tuners.

Excellent, great to hear! The same here as well, seems that was the fix. Whew 😜.

**Pull request closed without merging**
