### PR TITLE
Tunercnt

### PR DESCRIPTION
**Pull request by arrmo**
@DanAustinGH - for your review.

This is to,
Track and Correct tuner instance, ceton vs. fhdhr
=> don't use fhdhr instance number, rather ceton itself.

### CODE REVIEW

**Comment by DanAustinGH** [comment]
Looks simple and clean.  Merging.

And unrelated, but after a bit of an ebay slap-fest I won a PCIe 6.  Once here I will ponder deeper on how best to handle 2 or more Ceton devices.

**Comment by arrmo** [comment]
> Looks simple and clean. Merging.

Thanks! As always, yell if issues 😄.



> And unrelated, but after a bit of an ebay slap-fest I won a PCIe 6. Once here I will ponder deeper on how best to handle 2 or more Ceton devices.

Nice! I really do like mine - as you say ... 2 or more devices, also how to auto-get the tuner count. And then the slight "gotcha" of PCIe 😜

**Comment by DanAustinGH** [comment]
I could cheat and just 'clone' the plug-in to a ceton2 and add the 2nd device that way.  But I will look to do it right.  Same with tuner count.  The only two common values are 4 and 6.  We could default to 4 and leave it to the user to increase it if they want.  I should have the new card by Monday, and can start evaluating both feature sets then.

**Comment by arrmo** [comment]
Sounds great!

**Pull request merged**
