### PR TITLE
Add Threading Lock, to avoid CPU soft lockup

### PR DESCRIPTION
**Pull request by arrmo**
That occur in the case of simultaneous incoming tuner requests.
Now handled sequentially.

Also addresses delays in tuner stopping (and status messages
from Ceton), to avoid being in the "wrong" state.

### CODE REVIEW

**Comment by DanAustinGH** [comment]
Looks good to me.  I like the stopPending addition.

**Comment by arrmo** [comment]
> Looks good to me. I like the stopPending addition.

Thanks! And yes, this allows the "slow" transition to be handled (and recovered) correctly.

I think I need you to merge in / approve the PR 😆.

**Comment by DanAustinGH** [comment]
Indeed I do.  I realized that as I fell asleep.

**Comment by arrmo** [comment]
LOL - no worries! 🤣 

Thanks! And of course, yell if you see any issues.

**Pull request merged**
