### PR TITLE
Add rtp support for PCIe card(s)

### PR DESCRIPTION
**Pull request by arrmo**
@DanAustinGH, the one I mentioned 😄 

Adds rtp support for PCIe - like we had discussed in the (long) thread, needs to use the "pcie" IP address, not Ceton => rtp from 192.168.200.2 ... but made it a configurable variable, in case.

Yell if any concerns. Thanks!

### CODE REVIEW

**Comment by DanAustinGH** [comment]
How do you determine the PCIe IP address?

Did you get a chance to benchmark the time to tune a channel for each method and CPU load?

I do think working RTP is worth having, but I'd also like to keep the direct hardware method unless it has a noticeable performance hit...

**Comment by arrmo** [comment]
> How do you determine the PCIe IP address?

I was wondering what to call this, to avoid confusion 🤣. I'm open to ideas. But it's the local PC IP address, on the same subnet as the Ceton => it's where the Ceton RTP streams to, to be able to feed it in from there. Make sense?


> Did you get a chance to benchmark the time to tune a channel for each method and CPU load?

Not yet - but not forgotten! My issue is that I have been seeing error with the latest streaming updates - gradually getting worse with time running. This seems to work around it for now ... so making this change, then I can try to debug the dropped frames.


> I do think working RTP is worth having, but I'd also like to keep the direct hardware method unless it has a noticeable performance hit...

Agreed! I want that as well, just need to resolve the dropped frames. This gives me breathing room to do that ... LOL.

**Comment by arrmo** [comment]
Hang on for a minute please - may have found something!

**Comment by arrmo** [comment]
OK, found a bit of a snag. The Ceton allows direct OR rtp, not both simultaneously. I see that if I enable rtp, I can't pull from the device (i.e. cat). That sort of makes sense, and easy to add the logic to not StartStop if using direct ... checked that here, and it works. Oh, and ... "why didn't this happen before?". Because - the IP and port were being rejected before (by Ceton) ... I corrected that, and now the conflict (as it actually does enable rtp).

The snag - it messes with your approach of checking STOPPED or PLAYING from the Ceton (if using direct, as rtp can't be started). The tuner info is still correct in fHDHR, but not for Ceton. So ... keep track of the state separately (for direct?).

Thoughts?

Thanks!

**Comment by DanAustinGH** [comment]
We have a method to determine the state for rtp and for direct, so we may just to fiddle with it a bit.  I do not see an problem with the module only being able to support on mode or the other.

I considered trying to maintain tuner state, but since the standalone can be whacked by other clients or lose power when the fHDHR host does not, I realized it was going to get ugly.  I think that is far less likely on the PCIe, I can still think of ways it might happen.

**Comment by arrmo** [comment]
> We have a method to determine the state for rtp and for direct

Sorry, not sure I fully follow - how to detect for direct?



> I can still think of ways it might happen.

Agreed, but also not sure there is really a way to avoid it - in either case (even rtp, another rogue device could take over, right?). I guess no matter what, no answer is really foolproof. 

And actually, as fHDHR keeps it's own status - it won't allocate a tuner it thinks is in use. So not sure we really need to detect then at the Ceton level?

Thinking out loud, by all means disagree!

**Comment by DanAustinGH** [comment]
I thought we worked that out in the other thread, I will have to go re-read it.

RTP is the method most vulnerable to hijacking.  If you want to try your hand at tuner tracking for the direct method that works for me.

**Comment by arrmo** [comment]
> I thought we worked that out in the other thread, I will have to go re-read it.

We may have, and I just forgot - or didn't get it 🤣 


> RTP is the method most vulnerable to hijacking.

Agreed!

> If you want to try your hand at tuner tracking for the direct method that works for me.

Sure, will take a look! The good thing is - fHDHR at the "top" level is tracking correctly.

**Comment by arrmo** [comment]
OK, think I found a way to detect tuner usage ... rtp and direct (device) both. Trying to code here, seems to work. Want me to push a PR, so you can test it out as well?

I also added some items to the web interface, to help with display during debugging 😄.

Thanks!

**Comment by DanAustinGH** [comment]
Definitely submit the changes and I will review as soon as I can...

**Comment by arrmo** [comment]
Will do! Slight redirect ... latest upstream changes break things - let me dig.

**Comment by arrmo** [comment]
Updating my code, not a huge issue, but ... `stream_method` seems to have gone away? Thinking it's a different name now, but ... @deathbybandaid - with your changes, not sure how I determine `direct` or `rtp` in the plugin now?

Thanks!

**Comment by deathbybandaid** [comment]
`stream_args["method"​]`

The stream_args dict is passed to the `get_channel_stream` function.

There's other information there that has value.

**Comment by arrmo** [comment]
FYI, I removed my check for now - force it, but then,
```
  File "/mnt/ProgSSD/fHDHR/fHDHR/streammanager/stream_obj.py", line 24, in __init__
    self.setup_channel_stream()
  File "/mnt/ProgSSD/fHDHR/fHDHR/streammanager/stream_obj.py", line 91, in setup_channel_stream
    if self.tuner_needed:
  File "/mnt/ProgSSD/fHDHR/fHDHR/streammanager/stream_obj.py", line 43, in tuner_needed
    if self.stream_args["method"] == "passthrough":
KeyError: 'method'
2022-03-02T03:49:09Z {'REMOTE_ADDR': '192.168.2.64', 'REMOTE_PORT': '36690', 'HTTP_HOST': 'linuxserver.rkmorris.home:5006', (hidden keys: 20)} failed with KeyError
```

Thanks!

**Comment by deathbybandaid** [comment]
Toss a print line in or what stream_args show in ceton, also don't set self.method like that

**Comment by arrmo** [comment]
Funny, had done just exactly that 🤣. We are in sync!
```
{'channel': '593', 'channel_name': 'Golf HD', 'channel_callsign': 'Golf HD', 'origin': 'ceton', 'accessed': 'http://linuxserver.rkmorris.home:5006/api/tuners?method=stream&channel=65089df3-ff53-45b4-8656-9a0844d4edd8&origin=ceton', 'base_url': 'http://linuxserver.rkmorris.home:5006', 'client': '192.168.2.64', 'client_id': 'be7dc00c-5f63-4e9a-952d-a692d0559e6a', 'origin_quality': None, 'bytes_per_read': 1152000, 'buffer_size': 3, 'stream_restore_attempts': 3}
{'channel': '593', 'channel_name': 'Golf HD', 'channel_callsign': 'Golf HD', 'origin': 'ceton', 'accessed': 'http://linuxserver.rkmorris.home:5006/api/tuners?method=stream&channel=65089df3-ff53-45b4-8656-9a0844d4edd8&origin=ceton', 'base_url': 'http://linuxserver.rkmorris.home:5006', 'client': '192.168.2.64', 'client_id': 'c44ad89e-3af1-4edc-b34e-984e49e75ec9', 'origin_quality': None, 'bytes_per_read': 1152000, 'buffer_size': 3, 'stream_restore_attempts': 3}
```

Didn't want to set that, but I need it in `startstop_ceton_tuner`, and it's not available there 😞. So was adding this in to be able to use it in startstop.

**Comment by deathbybandaid** [comment]
Just pushed  revert

**Comment by arrmo** [comment]
FYI, direct working also. Leaving a test running overnight now ... vlc, two windows - /dev directly into vlc, and one through fHDHR, with debug loglevel. Let's see 😄.

Thanks!

**Comment by deathbybandaid** [comment]
https://github.com/fHDHR/fHDHR/pull/296 fixes `close_stream` and also adds a new `prime_stream` for plugins that need a head-start before fHDHR starts pulling content

**Comment by arrmo** [comment]
That works, thanks! FYI, just one that I noticed ... combination type thing (only happens with loglevel = noob, and ffmpeg ... not with direct!), Similar to a recent fix you included, but perhaps just missed ffmpeg streaming?
```
[2022-03-02 07:12:59,291] NOOB - Set your [logging]level to INFO if you wish to see more logging output.
[2022-03-02 07:13:50,833] ERROR - Unable to Stream: TunerError: Tuner Setup Failed (lazily handled): Tuner Setup Failed (lazily handled):KeyError 'noob'- /mnt/ProgSSD/fHDHR/fHDHR/streammanager/stream/__init__.py line 81
[2022-03-02 07:13:51,594] ERROR - Unable to Stream: TunerError: Tuner Setup Failed (lazily handled): Tuner Setup Failed (lazily handled):KeyError 'noob'- /mnt/ProgSSD/fHDHR/fHDHR/streammanager/stream/__init__.py line 81
```

**Comment by deathbybandaid** [comment]
I have no idea why that is happening to you. I cannot recreate

**Comment by deathbybandaid** [comment]
@arrmo try pulling new push for ffmpeg plugin

https://github.com/fHDHR/fHDHR_plugin_stream_ffmpeg/pull/9

**Comment by arrmo** [comment]
That works! Apologies if this was me - I thought I pulled all the latest plugins, but I could have missed one 😞.

OK, back to this update ... LOL. Actually, it's almost fully working here, now, with updates to the UI as well. Will try to get the PR in today, so you can look it over.

FYI, I will open a new (top level) issue, related to dropped frames (as I have mentioned). Have some results to share now, but let me clean them up first.

Thanks again!

**Comment by arrmo** [comment]
@DanAustinGH OK, the updated code - enjoy! 😄. Definitely let me know your thoughts. A few items to help explain,
1. this supports both rtp (udp) and direct for the pcie card
2. checks are done for both (in use) ... rtp streaming, or direct access
3. I tied in updating the UI, as it helped me to debug. By all means, propose naming changes if you want!
4. like I had mentioned, I have to "block" starting rtp streaming, if direct is desired => they are mutually exclusive, the pcie card outputs to rtp OR /dev (direct), not both

@deathbybandaid, by all means comment as well.

Thanks!

PS: A little screenshot from the "updated" UI ... oh, and I see that my daughter is using Plex right now 🤣 
image

**Comment by DanAustinGH** [comment]
Looks good.  I may have not called the hw in use function if using RTP, but I see you dealt with it in the function.
The only minor nit I have is your logging states that the device is PCIe, which can be assumed for direct hardware, but not RTP.

And also super minor, but in the screenshot it looks odd if Transport is 'Stopped' and in HW State is in Use.  And that made me think what would my non-PCI tuner report for HW state.  We might want it to manually set it to 'N/A' for remote devices or not display it at all.

Neither are enough to prevent me from merging, unless you want to tweak them before a merge.

**Comment by arrmo** [comment]
> I may have not called the hw in use function if using RTP, but I see you dealt with it in the function.

"in use" is meant to indicate direct access, to the device. I'm all for different naming - just propose something and I'll change it. Really no issue at all!



> The only minor nit I have is your logging states that the device is PCIe, which can be assumed for direct hardware, but not RTP.

True, Want me to change that note somehow? I was there as I was working my way through :smile:



> And that made me think what would my non-PCI tuner report for HW state. We might want it to manually set it to 'N/A' for remote devices or not display it at all.

Good point! I could change HW State to N/A for remote, like you say. I'm definitely good with that!

> Neither are enough to prevent me from merging, unless you want to tweak them before a merge.

Let's tweak it, no issue. I'm game 😄. Just let me know your thoughts on these, and I'll update.

**Comment by DanAustinGH** [comment]
How about merging Transport and HW and use these states (idle/RTP/Direct).  For the logging just remove 'PCIe' fro line 254 in __init__.py

**Comment by arrmo** [comment]
Will do! Give me just a little bit - as I noticed, daughter is connected, can't restart it right now ... LOL.

**Comment by arrmo** [comment]
Like this?
image

**Comment by DanAustinGH** [comment]
Yes!  People with stand-alone devices will only See idle or RTP and the PCIe crowd will see what they are configured for.

**Comment by arrmo** [comment]
Agree with you! This does look better, appreciate the suggestion. Another set of eyes always good 👍 

Pushed this update, I think we're aligned - but feel free to disagree.

Thanks!

**Comment by DanAustinGH** [comment]
I'm going to merge this and will try to get my stand-alone environment updated for testing today...

**Comment by arrmo** [comment]
Sounds great, thanks! If you see any issues - poke me. We'll get it working for both 👍

**Comment by DanAustinGH** [comment]
This broke the stand-alone device.  The logic to not make the Start API call looks good, but my RTP streams failed with streaming set to ffmpeg or direct.  I changed it to if not self.ceton_pcie and my device is working again.

**Comment by arrmo** [comment]
> I changed it to if not self.ceton_pcie and my device is working again.

Do you mean in the Start API? Is it detecting your stand-alone device as PCIe for some reason? Perhaps print that variable out, so we can check it?

Other than this one thing - the rest working? BTW, from the Ceton UI => manually start one tuner streaming (to never never land 😜) ... the UI should detect it.

Thanks!

**Comment by arrmo** [comment]
Just printed out the variables, and the output is exactly as expected. Then it hit me ... I did have to make some changes to adapt to upstream mods. Did you also pull in the latest from the ffmpeg plugin, and fHDHR itself? Meaning ... are those main branches fully updated on your local?

Thanks!

**Comment by arrmo** [comment]
So glad it's not just me who does that 😜 

Thanks!

**Comment by arrmo** [comment]
No worries at all! I have done that way too many times myself. Glad it's all working for you!

**Comment by deathbybandaid** [comment]
Then there's me over here merging channels into the origins system.

Channels system worked great back when I only had to support a single origin.

**Comment by DanAustinGH** [comment]
I was worried the death of Locast would demotivate development around the emulator/proxy apps.  I am happy to see that has not been the case....

**Comment by arrmo** [comment]
Agreed! I think this works really well - I even have some plugins I'd like get to, when I have time 😄

**Comment by arrmo** [comment]
BTW, not forgotten about the direct vs. rtp / ffmpeg startup timing. Trying to find a way to measure it automated. I'm open to suggestions!

**Comment by DanAustinGH** [comment]
Perfect is the enemy of good.  Plex, emby and other players will all introduce some variance to the measurements.  I'm just curious if one 'feels' quicker than the other.  For me  Emby usually tunes in 2~3 seconds.  I've had a few .5 second tune and a few 5 second.  I suspect that direct will be a bit quicker and a bit more consistent, having eliminated a bit of network traffic and maybe benefiting from the direct stream not having the UDP packet overhead.

**Comment by arrmo** [comment]
> Perfect is the enemy of good.

Agreed! You must be an engineer (too) 😜 

> For me Emby usually tunes in 2~3 seconds.

Very interesting timing. I say that because ... the answer was staring me in the face, finally smacked me. Here is what I figured out (yell if you disagree of course!),

Use a client (I chose ffmpeg), that I can time => run a fixed duration of video, then remove that duration from the total time ... the remaining time is startup. Agreed so far? So I went with,
```
time ffmpeg -i 'http://192.168.2.64:5006/api/tuners?method=stream&channel=593&origin=ceton' -t 30 -f null /dev/null
```
This will time ffmpeg, connecting to the server, tuning to channel 593, and processing 30 seconds of video (dumping it to the trash). I started with 30 seconds in case of any startup artifacts / glitches, make sure the video is running smooth (which 30 seconds should ensure). The result?
```
real    0m33.337s
user    0m5.556s
sys     0m0.166s
```
Take off 30 seconds => startup is 3.3 seconds. Not too far from what you mentioned. Of course, different clients will be different, but that's on the client then 😆. I then tried 3 seconds of video, got,
```
real    0m6.500s
user    0m0.368s
sys     0m0.041s
```
So 3.5 seconds of startup ... works for me! Don't save this number quite yet - as I have been messing with code here, let me undo some things, get real numbers.

Oh, and something to noodle on. I was also thinking about CI/CD in the back of my mind, cases to run automated, confirm the build is good. Interestingly enough, the command above returns 0 ... as expected. If I pick a bogus channel, I get 1. Woohoo, this could be a CI/CD test, agreed?

**Comment by arrmo** [comment]
OK, 3 runs each, rtp and direct, averaged,
```
rtp: 2.7 sec
direct: 2.2 sec
```

Not a huge difference, but a bit quicker direct, as you though. BTW, I do see some interesting things in the two cases, that may lead to more optimization yet?
1. rtp
```
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[mpegts @ 0x565292b5d140] Could not find codec parameters for stream 1 (Audio: ac3 (AC-3 / 0x332D4341), 0 channels, fltp): unspecified sample rate
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[mpegts @ 0x565292b5d140] Could not find codec parameters for stream 2 (Unknown: none ([5][0][0][0] / 0x0005)): unknown codec
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[mpegts @ 0x565292b5d140] Could not find codec parameters for stream 3 (Unknown: none ([5][0][0][0] / 0x0005)): unknown codec
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
```
2. direct, client side
```
[mpegts @ 0x560886e82ec0] Stream #0: not enough frames to estimate rate; consider increasing probesize
[mpegts @ 0x560886e82ec0] Could not find codec parameters for stream 0 (Video: mpeg2video ([2][0][0][0] / 0x0002), none(tv)): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[mpegts @ 0x560886e82ec0] Could not find codec parameters for stream 1 (Audio: ac3 (AC-3 / 0x332D4341), 0 channels, fltp): unspecified sample rate
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[mpegts @ 0x560886e82ec0] Could not find codec parameters for stream 2 (Unknown: none ([5][0][0][0] / 0x0005)): unknown codec
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[mpegts @ 0x560886e82ec0] Could not find codec parameters for stream 3 (Unknown: none ([5][0][0][0] / 0x0005)): unknown codec
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
```

Very similar in both cases
Thinking I closed my AP here 😜. Thanks!

**Comment by DanAustinGH** [comment]
I like it.  Simple and re-producible without worrying about the media server adding its own delay.  I'm not sure how much optimization with yield.  I think increasing probesize might actually slow things down since it is just a stream copy.

And nice to see the actual numbers.  I am considering trying to pick up a PCIe 6 tuner to replace the current 6 tuner and HDHR 3 tuner I keep as a spare.  The .5 second is not a big difference, but I'd eliminate a good bit of traffic off the home network...
 Many thanks for the contributions!

**Comment by arrmo** [comment]
> I am considering trying to pick up a PCIe 6 tuner to replace the current 6 tuner

Agreed! I do like the internal card => network traffic is just the PCIe bus 😄 



> HDHR 3 tuner I keep as a spare

@deathbybandaid may want to hear about this - he has been looking for SSDP output from real HW.

> Many thanks for the contributions!

Happy to help if I can!

**Comment by arrmo** [comment]
Well ... a slight update 🤣. Improved timing a bit, without any real downside ... I realized that I had `buffer_size` set to 3. But there is no real upside to that, as for a real-time / streaming input ... you can't gain any ground on the source => and this is just buffering time up front, which really is only delay. So - changed it to 0, confirmed overnight no higher rate of dropped packets, but updating startup timing! Now ...
```
rtp: 1.8 sec
direct: 1.3 sec
```

I have been also fiddling with trying to specify the input format, to speed up startup in ffmpeg in case detection is limiting ... but even in the broken case (screwed up parameters, by me 😆), it's ~ 1.2-1.4 sec. So I'm not thinking I'll get much below the times above. Time to move on to the next item ... which, BTW - I'm going to open a new "issue". Will explain it there, and feel free to assign it to me.

**Comment by DanAustinGH** [comment]
Yeah, we talked about the lack of need for buffering for the Ceton.  You may be able to shave another .25~.5 by reducing the bytes_per_read.  The trade off there is the CPU load will go up.  Since each buffer read represented about .7 seconds of delay there is not a huge about to save here.

Off to see if I forgot to reset the buffer values on my install...

**Comment by arrmo** [comment]
> Yeah, we talked about the lack of need for buffering for the Ceton. You may be able to shave another .25~.5 by reducing the bytes_per_read. The trade off there is the CPU load will go up. Since each buffer read represented about .7 seconds of delay there is not a huge about to save here.

Agreed! Was thinking that too - perhaps a slight savings. Like you say, a tradeoff.



> Off to see if I forgot to reset the buffer values on my install...

So you have 3 as well currently? Or some other value?

**Comment by DanAustinGH** [comment]
I had mine at 1.  Moving to 0 did not make a difference on the 1st tune.  Will monitor to see if it seems quicker, but since the likely improvement is just under a second, I may well not notice.

**Comment by arrmo** [comment]
Agreed! The delta is pretty small now ... I shaved 1 second going from 3 to 0 ... so your delta is likely ~ 0.33 sec, not really noticeable. I'm using time to measure it, but 0.33 sec won't show much when watching it 😜

**Comment by DanAustinGH** [comment]
I'm going to ponder how we might be able to have multiple Ceton devices.  I have a bid in on a 6 tuner PCIe, and see a few USB-4 devices, which would be similar to the PCIe for hardware access, and I could see people interesting having a mix in use.

Something along the line of adding a config variable Ceton_device_count then loop over reading in ceton_ip_{device#}, pcie_ip_{device#} and tuners_{device#}.  Need to update the properties as well which appears a bit trickier, but not impossible.

**Comment by arrmo** [comment]
Sounds great! And to our earlier discussion - auto-detect the number of tuners (on a device), not hard coded?

Thanks!

**Comment by DanAustinGH** [comment]
Will have to see what is possible once/if I can acquire a 2nd devcie...

**Pull request merged**
