### PR TITLE
Add auto refresh for ceton

### PR DESCRIPTION
**Pull request by arrmo**
More details [here](https://github.com/fHDHR/fHDHR/issues/240#issuecomment-1032092736). Auto-refresh for ceton.

### CODE REVIEW

**Comment by arrmo** [comment]
@DanAustinGH, just checking - OK with you? No issue if not - just yell 😄.

Thanks!

**Comment by DanAustinGH** [comment]
Sorry, I don't get notified of new issues/pr on this repo, so weeks can go by before I notice them.  Just tag me when you post and I can make sure these are handled timely....

**Comment by arrmo** [comment]
Thanks! Just wasn't sure if I had something wrong or not 😄.

Will have another coming in a couple / few days - rtp (udp) working with the PCIe!

> Sorry, I don't get notified of new issues/pr on this repo, so weeks can go by before I notice them. Just tag me when you post and I can make sure these are handled timely....

NP at all! Will do. Thanks again.

**Comment by DanAustinGH** [comment]
Will watch for it...

**Pull request merged**
